DROP SEQUENCE reservation_seq;
DROP SEQUENCE facility_seq;
DROP TABLE KG_SCHEDULE;
DROP TABLE KG_RESERVATION;
DROP TABLE KG_FACILITY;
DROP TABLE KG_CATEGORY;
DROP TABLE KG_USER;


CREATE TABLE KG_USER(
		U_ID VARCHAR2(20) NULL ,
		U_PWD VARCHAR2(20) NOT NULL,
		U_NAME VARCHAR2(30) NULL ,
		U_TEL VARCHAR2(20) NULL ,
		U_EMAIL VARCHAR2(30) NULL ,
		U_ISMANAGER VARCHAR2(10) DEFAULT 'FALSE' NOT NULL
);

CREATE TABLE KG_CATEGORY(
		C_NAME                        		VARCHAR2(20)		 NULL ,
		C_COLOR                       		VARCHAR2(20)		 NULL ,
		C_IMGNAME                     		VARCHAR2(30)		 NULL 
);

CREATE TABLE KG_FACILITY(
		F_NUM                         		NUMBER(30)		 NULL ,
		C_NAME                        		VARCHAR2(20)		 NULL ,
		F_NAME                        		VARCHAR2(30)		 NULL ,
		F_ADDRESS                     		VARCHAR2(30)		 NULL ,
		F_TEL                         		VARCHAR2(20)		 NULL ,
		F_PRICE                       		NUMBER(30)		 DEFAULT 0		 NULL ,
		F_MAX                         		NUMBER(20)		 NULL ,
		F_OPENTIME                    		DATE		 NULL ,
		F_CLOSETIME                   		DATE		 NULL ,
		F_MAXTIME                     		DATE		 NULL ,
		F_IMGNAME                     		VARCHAR2(30)		 NULL 
);

CREATE TABLE KG_RESERVATION(
		R_NUM                         		NUMBER(30)		 NULL ,
		R_NAME                        		VARCHAR2(30)		 NULL ,
		U_ID                          		VARCHAR2(20)		 NOT NULL,
		F_NUM                         		NUMBER(30)		 NOT NULL,
		R_DATE                        		DATE		 NULL ,
		R_STARTTIME                   		DATE		 NULL ,
		R_ENDTIME                     		DATE		 NULL ,
		R_TYPE                        		VARCHAR2(10)		 NULL 
);

CREATE TABLE KG_SCHEDULE(
		U_ID                          		VARCHAR2(20)		 NULL ,
		R_NUM                         		NUMBER(30)		 NULL 
);


ALTER TABLE KG_USER ADD CONSTRAINT IDX_KG_USER_PK PRIMARY KEY (U_ID);

ALTER TABLE KG_CATEGORY ADD CONSTRAINT IDX_KG_CATEGORY_PK PRIMARY KEY (C_NAME);

ALTER TABLE KG_FACILITY ADD CONSTRAINT IDX_KG_FACILITY_PK PRIMARY KEY (F_NUM);
ALTER TABLE KG_FACILITY ADD CONSTRAINT IDX_KG_FACILITY_FK0 FOREIGN KEY (C_NAME) REFERENCES KG_CATEGORY (C_NAME);

ALTER TABLE KG_RESERVATION ADD CONSTRAINT IDX_KG_RESERVATION_PK PRIMARY KEY (R_NUM);
ALTER TABLE KG_RESERVATION ADD CONSTRAINT IDX_KG_RESERVATION_FK0 FOREIGN KEY (F_NUM) REFERENCES KG_FACILITY (F_NUM);
ALTER TABLE KG_RESERVATION ADD CONSTRAINT IDX_KG_RESERVATION_FK1 FOREIGN KEY (U_ID) REFERENCES KG_USER (U_ID);

ALTER TABLE KG_SCHEDULE ADD CONSTRAINT IDX_KG_SCHEDULE_PK PRIMARY KEY (U_ID, R_NUM);
ALTER TABLE KG_SCHEDULE ADD CONSTRAINT IDX_KG_SCHEDULE_FK0 FOREIGN KEY (U_ID) REFERENCES KG_USER (U_ID);
ALTER TABLE KG_SCHEDULE ADD CONSTRAINT IDX_KG_SCHEDULE_FK1 FOREIGN KEY (R_NUM) REFERENCES KG_RESERVATION (R_NUM);


CREATE SEQUENCE facility_seq;
CREATE SEQUENCE reservation_seq;
